# Generated by Django 4.0.5 on 2022-08-04 06:16

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('assigned_to', models.ManyToManyField(related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('COMPLETED', 'COMPLETED'), ('APPROVAL PENDING', 'APPROVAL PENDING'), ('DEADLINE PASSED', 'DEADLINE PASSED')], max_length=200)),
                ('reference', models.URLField(blank=True, help_text='Upload Your Work Via Link', max_length=300, null=True)),
                ('assigned_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.work')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='profile_pic/')),
                ('role', models.CharField(blank=True, choices=[('President', 'President'), ('Head', 'Head'), ('Member', 'Member')], max_length=200)),
                ('team', models.CharField(blank=True, choices=[('Technical', 'Technical'), ('Design', 'Design'), ('Event Management', 'Event Management'), ('Content', 'Content'), ('Marketing', 'Marketing')], max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='user', unique=True)),
                ('description', models.TextField()),
                ('awards', models.CharField(max_length=500)),
                ('Skillset', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
