# Generated by Django 4.0.5 on 2022-07-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(blank=True, choices=[('Technical', 'Technical'), ('Design', 'Design'), ('Event Management', 'Event Management'), ('Content', 'Content'), ('Marketing', 'Marketing')], max_length=200),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('COMPLETED', 'COMPLETED'), ('APPROVAL PENDING', 'APPROVAL PENDING'), ('DEADLINE PASSED', 'DEADLINE PASSED')], max_length=200),
        ),
    ]
